# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# To override a parameter, ensure the structure matches the ConfigContainer
# and its sub-configurations (e.g., model, train, etc.)
# Top-level ConfigContainer fields are dataclasses themselves

model:
  seq_length: 4096
  tensor_model_parallel_size: 2
  pipeline_model_parallel_size: 1
  context_parallel_size: 1
  virtual_pipeline_model_parallel_size: null
  expert_model_parallel_size: 8
  expert_tensor_parallel_size: 1
  cross_entropy_fusion_impl: "te"
  use_te_rng_tracker: true
  external_cuda_graph: true
  cuda_graph_scope: "attn"
  num_moe_experts: 8
  num_layers: 3
  moe_layer_freq: [0, 1, 1]
  pipeline_model_parallel_layout: null
  moe_router_num_groups: 1
  moe_router_group_topk: 1
  moe_router_fusion: true
  moe_permute_fusion: true
  apply_rope_fusion: true

rng:
  te_rng_tracker: true

train:
  global_batch_size: 32
  micro_batch_size: 1
  train_iters: 25
  eval_iters: 0

dist:
  enable_megatron_core_experimental: true

checkpoint:
  # Directory to save to. If null, no checkpoint will be saved.
  save: null

logger:
  log_interval: 1

ddp:
  check_for_nan_in_grad: false
  check_for_large_grads: false

mixed_precision:
  grad_reduce_in_fp32: false

profiling:
  # For optional fields in the config, specify the target to instantiate the object.
  _target_: megatron.bridge.training.config.ProfilingConfig
  use_nsys_profiler: true
  profile_step_start: 10
  profile_step_end: 11
  profile_ranks: [0]
  record_shapes: false
  use_pytorch_profiler: false
